### ISSUE TITLE
Attaching to an external DOM 

### ISSUE THREAD

**Issue by system123** [soal/vue-mapbox-geocoder#1]
How can I attach this to an external DOM element? My search bar is located outside of my map, and I would like the geocoder to do the same. So far I have tried the following:

[Searchbar.vue](https://gist.github.com/system123/6e44b59db7214bebc7fd9afa929ab6c0)

But I get the following error when calling the query() method:

[Vue warn]: Error in callback for watcher "defaultInput": "TypeError: this._loadingEl is undefined"

found in

---> <Searchbar> at src/components/Searchbar.vue
       <VToolbar>
         <VApp>
           <App> at src/App.vue
             <Root>
vue.esm.js:591
TypeError: this._loadingEl is undefined
Stack trace:
_geocode@webpack-internal:///./node_modules/@mapbox/mapbox-gl-geocoder/lib/index.js:167:5
query@webpack-internal:///./node_modules/@mapbox/mapbox-gl-geocoder/lib/index.js:264:5
defaultInput@webpack-internal:///./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/Searchbar.vue:46:25
run@webpack-internal:///./node_modules/vue/dist/vue.esm.js:3232:11
flushSchedulerQueue@webpack-internal:///./node_modules/vue/dist/vue.esm.js:2980:5
nextTick/<@webpack-internal:///./node_modules/vue/dist/vue.esm.js:1836:9
flushCallbacks@webpack-internal:///./node_modules/vue/dist/vue.esm.js:1757:5

**Comment by system123** [comment]
I implemented a stand-alone geocoder for this.

**Comment by petemolinero** [comment]
@system123 How did you end up doing this? I'd like to do a standalone geocoder as well, without the map.
