### ISSUE TITLE
Base mixin deprecated breaks plugin

### ISSUE THREAD

**Issue by henningko** [soal/vue-mapbox-geocoder#2]
Hi,

With this [commit](https://github.com/soal/vue-mapbox/commit/bd68fa86534c37ed575e7e632c536546ac595da7#diff-1c90ff38a08209f9ebd4d05d1e43358e) the base mixin is dropped, which causes the plugin to stop working. It seems like things have moved into "withEvents.js", however, this is not globally available as a mixin.

Any ideas on how to remedy?

**Comment by soal** [comment]
I plan to release an update to this to play along with VueMapbox and Mapbox pllugin API changes by January 20th.

**Comment by soal** [comment]
Fixed in 0.2
